version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: dev/Dockerfile
    ports:
     - "8080:8080"
     - "8888:8888"
    volumes:
     - ./:/srv
     - ./dev/.bash_history:/root/.ash_history
